version: "3.9"

services:
  # Server Api
  server:
    container_name: server-ci-cd
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"
    env_file:
      - .env
    entrypoint: npm start
    networks:
      - server-nw

  # Client Api
  client:
    container_name: client-ci-cd
    depends_on:
      - server
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    expose:
      - "${CLIENT_PORT}"
    env_file:
      - .env
    entrypoint: tail -f /dev/null
    networks:
      - server-nw

networks:
  server-nw:
    driver: bridge
