name: DockerCompose Actions Workflow
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker-compose up -d
      - name: ShowContainers
        run: docker ps
      - name: Running Tests
        run: docker-compose exec -T server sh -c "npm test"
      # heroku test
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: learn-ci-cd
        run: heroku container:login

      - name: Pushing Images
        run: echo angelportinari17@gmail.com | heroku container:push --recursive --app env.HEROKU_APP

      - name: Relase Images
        run: echo angelportinari17@gmail.com | heroku container:release web --app env.HEROKU_APP
