name: DockerCompose Actions Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker-compose up -d
      - name: TestServer
        run: curl localhost:8181
